// app/staff/login/page.tsx
'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { FormEvent, useState } from 'react'
import AppTopbar from '@/components/AppTopbar'
import PageHeader from '@/components/PageHeader'

async function readError(response: Response) {
  const data = (await response.json().catch(() => null)) as { statusMessage?: string } | null
  return data?.statusMessage
}

export default function StaffLoginPage() {
  const router = useRouter()
  const [form, setForm] = useState({ email: '', password: '' })
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')

  async function login(event: FormEvent) {
    event.preventDefault()
    setErrorMessage('')
    setIsSubmitting(true)

    try {
      const response = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form),
      })

      if (!response.ok) {
        setErrorMessage((await readError(response)) ?? 'Login failed. Please try again.')
        return
      }

      router.push('/staff')
    } catch {
      setErrorMessage('Login failed. Please try again.')
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <main className="app-surface">
      <div className="app-shell">
        <AppTopbar />

        <PageHeader
          eyebrow="Staff login"
          title="Access Crown Valet operations"
          description="Sign in with your email and password to access staff operations."
        />

        <section className="app-card">
          <form className="check-in-form" onSubmit={login}>
            <div className="form-section">
              <label className="field">
                <span>Email</span>
                <input
                  value={form.email}
                  onChange={(event) => setForm({ ...form, email: event.target.value })}
                  type="email"
                  autoComplete="email"
                  name="email"
                  placeholder="you@example.com"
                  required
                />
              </label>

              <label className="field">
                <span>Password</span>
                <input
                  value={form.password}
                  onChange={(event) => setForm({ ...form, password: event.target.value })}
                  type="password"
                  autoComplete="current-password"
                  name="password"
                  placeholder="••••••••"
                  required
                />
              </label>
            </div>

            {errorMessage ? <p className="form-error">{errorMessage}</p> : null}

            <div className="form-submit">
              <button className="button primary" type="submit" disabled={isSubmitting}>
                {isSubmitting ? 'Signing in…' : 'Sign in'}
              </button>
            </div>
          </form>

          <p className="signup-link">
            Don&apos;t have an account? <Link href="/staff/signup">Create one</Link>
          </p>
        </section>
      </div>

      <style jsx>{`
        .signup-link {
          margin-top: 1.25rem;
          text-align: center;
          font-size: 0.875rem;
          color: var(--color-ink);
          opacity: 0.7;
        }

        .signup-link :global(a) {
          color: var(--color-gold);
          text-decoration: none;
          font-weight: 600;
        }

        .signup-link :global(a:hover) {
          text-decoration: underline;
        }
      `}</style>
    </main>
  )
}

// pages/staff/login.vue
<script setup lang="ts">
const form = reactive({ email: '', password: '' })
const isSubmitting = ref(false)
const errorMessage = ref('')

async function login() {
  errorMessage.value = ''
  isSubmitting.value = true

  try {
    await $fetch('/api/auth/login', {
      method: 'POST',
      body: form,
    })
    await navigateTo('/staff')
  } catch (error: unknown) {
    const msg =
      error && typeof error === 'object' && 'data' in error
        ? (error as { data?: { statusMessage?: string } }).data?.statusMessage
        : undefined
    errorMessage.value = msg ?? 'Login failed. Please try again.'
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <main class="app-surface">
    <div class="app-shell">
      <AppTopbar />

      <PageHeader
        eyebrow="Staff login"
        title="Access Crown Valet operations"
        description="Sign in with your email and password to access staff operations."
      />

      <section class="app-card">
        <form class="check-in-form" @submit.prevent="login">
          <div class="form-section">
            <label class="field">
              <span>Email</span>
              <input
                v-model="form.email"
                type="email"
                autocomplete="email"
                name="email"
                placeholder="you@example.com"
                required
              >
            </label>

            <label class="field">
              <span>Password</span>
              <input
                v-model="form.password"
                type="password"
                autocomplete="current-password"
                name="password"
                placeholder="••••••••"
                required
              >
            </label>
          </div>

          <p v-if="errorMessage" class="form-error">{{ errorMessage }}</p>

          <div class="form-submit">
            <button class="button primary" type="submit" :disabled="isSubmitting">
              {{ isSubmitting ? 'Signing in…' : 'Sign in' }}
            </button>
          </div>
        </form>
      </section>
    </div>
  </main>
</template>
