// app/staff/profile/page.tsx
'use client'

import { useRouter } from 'next/navigation'
import { FormEvent, useEffect, useState } from 'react'
import AppTopbar from '@/components/AppTopbar'
import PageHeader from '@/components/PageHeader'

type Me = {
  id: string
  name: string
  email: string
  role: string
}

async function readError(response: Response) {
  const data = (await response.json().catch(() => null)) as { statusMessage?: string } | null
  return data?.statusMessage
}

export default function StaffProfilePage() {
  const router = useRouter()
  const [me, setMe] = useState<Me | null>(null)
  const [form, setForm] = useState({
    currentPassword: '',
    newPassword: '',
    confirmPassword: '',
  })
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')
  const [successMessage, setSuccessMessage] = useState('')

  useEffect(() => {
    void fetch('/api/staff/me')
      .then((response) => response.json())
      .then(setMe)
      .catch(() => setMe(null))
  }, [])

  async function changePassword(event: FormEvent) {
    event.preventDefault()
    setErrorMessage('')
    setSuccessMessage('')
    setIsSubmitting(true)

    try {
      const response = await fetch('/api/staff/change-password', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form),
      })

      if (!response.ok) {
        setErrorMessage((await readError(response)) ?? 'Could not update password. Please try again.')
        return
      }

      setSuccessMessage('Password updated successfully.')
      setForm({ currentPassword: '', newPassword: '', confirmPassword: '' })
    } catch {
      setErrorMessage('Could not update password. Please try again.')
    } finally {
      setIsSubmitting(false)
    }
  }

  async function logout() {
    await fetch('/api/auth/logout', { method: 'POST' })
    router.push('/staff/login')
  }

  return (
    <main className="app-surface">
      <div className="app-shell">
        <AppTopbar />

        <PageHeader
          eyebrow="My profile"
          title="Account settings"
          description="Manage your staff account details."
        />

        <section className="app-card">
          <div className="form-section">
            <div>
              <p className="eyebrow">Account</p>
              <h2>Your details</h2>
            </div>
            <p>
              <strong>Name:</strong> {me?.name}
            </p>
            <p>
              <strong>Email:</strong> {me?.email}
            </p>
            <p>
              <strong>Role:</strong> {me?.role}
            </p>
          </div>
        </section>

        <section className="app-card">
          <form className="check-in-form" onSubmit={changePassword}>
            <div className="form-section">
              <div>
                <p className="eyebrow">Security</p>
                <h2>Change password</h2>
              </div>

              <label className="field">
                <span>Current password</span>
                <input
                  value={form.currentPassword}
                  onChange={(event) =>
                    setForm({ ...form, currentPassword: event.target.value })
                  }
                  type="password"
                  autoComplete="current-password"
                  name="currentPassword"
                  placeholder="••••••••"
                  required
                />
              </label>

              <label className="field">
                <span>
                  New password <strong>Min. 8 characters</strong>
                </span>
                <input
                  value={form.newPassword}
                  onChange={(event) => setForm({ ...form, newPassword: event.target.value })}
                  type="password"
                  autoComplete="new-password"
                  name="newPassword"
                  placeholder="••••••••"
                  minLength={8}
                  required
                />
              </label>

              <label className="field">
                <span>Confirm new password</span>
                <input
                  value={form.confirmPassword}
                  onChange={(event) =>
                    setForm({ ...form, confirmPassword: event.target.value })
                  }
                  type="password"
                  autoComplete="new-password"
                  name="confirmPassword"
                  placeholder="••••••••"
                  minLength={8}
                  required
                />
              </label>
            </div>

            {errorMessage ? <p className="form-error">{errorMessage}</p> : null}
            {successMessage ? <p className="form-success">{successMessage}</p> : null}

            <div className="form-submit">
              <button className="button primary" type="submit" disabled={isSubmitting}>
                {isSubmitting ? 'Updating…' : 'Update password'}
              </button>
            </div>
          </form>
        </section>

        <section className="app-card">
          <div className="form-section">
            <div>
              <p className="eyebrow">Session</p>
              <h2>Sign out</h2>
            </div>
            <p>End your current staff session.</p>
            <button className="button" type="button" onClick={() => void logout()}>
              Sign out
            </button>
          </div>
        </section>
      </div>
    </main>
  )
}

// pages/staff/profile.vue
<script setup lang="ts">
definePageMeta({
  middleware: 'staff-auth',
})

const { data: me } = await useFetch('/api/staff/me')

const form = reactive({
  currentPassword: '',
  newPassword: '',
  confirmPassword: '',
})

const isSubmitting = ref(false)
const errorMessage = ref('')
const successMessage = ref('')

async function changePassword() {
  errorMessage.value = ''
  successMessage.value = ''
  isSubmitting.value = true

  try {
    await $fetch('/api/staff/change-password', {
      method: 'POST',
      body: form,
    })
    successMessage.value = 'Password updated successfully.'
    form.currentPassword = ''
    form.newPassword = ''
    form.confirmPassword = ''
  } catch (error: unknown) {
    const msg =
      error && typeof error === 'object' && 'data' in error
        ? (error as { data?: { statusMessage?: string } }).data?.statusMessage
        : undefined
    errorMessage.value = msg ?? 'Could not update password. Please try again.'
  } finally {
    isSubmitting.value = false
  }
}

async function logout() {
  await $fetch('/api/auth/logout', { method: 'POST' })
  await navigateTo('/staff/login')
}
</script>

<template>
  <main class="app-surface">
    <div class="app-shell">
      <AppTopbar />

      <PageHeader
        eyebrow="My profile"
        title="Account settings"
        description="Manage your staff account details."
      />

      <section class="app-card">
        <div class="form-section">
          <div>
            <p class="eyebrow">Account</p>
            <h2>Your details</h2>
          </div>
          <p><strong>Name:</strong> {{ me?.name }}</p>
          <p><strong>Email:</strong> {{ me?.email }}</p>
          <p><strong>Role:</strong> {{ me?.role }}</p>
        </div>
      </section>

      <section class="app-card">
        <form class="check-in-form" @submit.prevent="changePassword">
          <div class="form-section">
            <div>
              <p class="eyebrow">Security</p>
              <h2>Change password</h2>
            </div>

            <label class="field">
              <span>Current password</span>
              <input
                v-model="form.currentPassword"
                type="password"
                autocomplete="current-password"
                name="currentPassword"
                placeholder="••••••••"
                required
              >
            </label>

            <label class="field">
              <span>New password <strong>Min. 8 characters</strong></span>
              <input
                v-model="form.newPassword"
                type="password"
                autocomplete="new-password"
                name="newPassword"
                placeholder="••••••••"
                minlength="8"
                required
              >
            </label>

            <label class="field">
              <span>Confirm new password</span>
              <input
                v-model="form.confirmPassword"
                type="password"
                autocomplete="new-password"
                name="confirmPassword"
                placeholder="••••••••"
                minlength="8"
                required
              >
            </label>
          </div>

          <p v-if="errorMessage" class="form-error">{{ errorMessage }}</p>
          <p v-if="successMessage" class="form-success">{{ successMessage }}</p>

          <div class="form-submit">
            <button class="button primary" type="submit" :disabled="isSubmitting">
              {{ isSubmitting ? 'Updating…' : 'Update password' }}
            </button>
          </div>
        </form>
      </section>

      <section class="app-card">
        <div class="form-section">
          <div>
            <p class="eyebrow">Session</p>
            <h2>Sign out</h2>
          </div>
          <p>End your current staff session.</p>
          <button class="button" type="button" @click="logout">Sign out</button>
        </div>
      </section>
    </div>
  </main>
</template>
