// app/staff/signup/page.tsx
'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { FormEvent, useState } from 'react'
import AppTopbar from '@/components/AppTopbar'
import PageHeader from '@/components/PageHeader'

async function readError(response: Response) {
  const data = (await response.json().catch(() => null)) as { statusMessage?: string } | null
  return data?.statusMessage
}

export default function StaffSignupPage() {
  const router = useRouter()
  const [form, setForm] = useState({ email: '', password: '', confirmPassword: '' })
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')

  async function signup(event: FormEvent) {
    event.preventDefault()
    setErrorMessage('')

    if (form.password !== form.confirmPassword) {
      setErrorMessage('Passwords do not match')
      return
    }

    setIsSubmitting(true)

    try {
      const response = await fetch('/api/auth/signup', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email: form.email, password: form.password }),
      })

      if (!response.ok) {
        setErrorMessage((await readError(response)) ?? 'Sign up failed. Please try again.')
        return
      }

      router.push('/staff/onboarding')
    } catch {
      setErrorMessage('Sign up failed. Please try again.')
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <main className="app-surface">
      <div className="app-shell">
        <AppTopbar />

        <PageHeader
          eyebrow="Create account"
          title="Join Crown Valet"
          description="Create your staff account to get started."
        />

        <section className="app-card">
          <form className="check-in-form" onSubmit={signup}>
            <div className="form-section">
              <label className="field">
                <span>Email</span>
                <input
                  value={form.email}
                  onChange={(event) => setForm({ ...form, email: event.target.value })}
                  type="email"
                  autoComplete="email"
                  name="email"
                  placeholder="you@example.com"
                  required
                />
              </label>

              <label className="field">
                <span>Password</span>
                <input
                  value={form.password}
                  onChange={(event) => setForm({ ...form, password: event.target.value })}
                  type="password"
                  autoComplete="new-password"
                  name="password"
                  placeholder="••••••••"
                  minLength={8}
                  required
                />
              </label>

              <label className="field">
                <span>Confirm password</span>
                <input
                  value={form.confirmPassword}
                  onChange={(event) =>
                    setForm({ ...form, confirmPassword: event.target.value })
                  }
                  type="password"
                  autoComplete="new-password"
                  name="confirm-password"
                  placeholder="••••••••"
                  required
                />
              </label>
            </div>

            {errorMessage ? <p className="form-error">{errorMessage}</p> : null}

            <div className="form-submit">
              <button className="button primary" type="submit" disabled={isSubmitting}>
                {isSubmitting ? 'Creating account…' : 'Create account'}
              </button>
            </div>
          </form>

          <p className="signup-login-link">
            Already have an account? <Link href="/staff/login">Sign in</Link>
          </p>
        </section>
      </div>

      <style jsx>{`
        .signup-login-link {
          margin-top: 1.25rem;
          text-align: center;
          font-size: 0.875rem;
          color: var(--color-ink);
          opacity: 0.7;
        }

        .signup-login-link :global(a) {
          color: var(--color-gold);
          text-decoration: none;
          font-weight: 600;
        }

        .signup-login-link :global(a:hover) {
          text-decoration: underline;
        }
      `}</style>
    </main>
  )
}

// pages/staff/signup.vue
<script setup lang="ts">
definePageMeta({ layout: false })

const form = reactive({ email: '', password: '', confirmPassword: '' })
const isSubmitting = ref(false)
const errorMessage = ref('')

async function signup() {
  errorMessage.value = ''

  if (form.password !== form.confirmPassword) {
    errorMessage.value = 'Passwords do not match'
    return
  }

  isSubmitting.value = true

  try {
    await $fetch('/api/auth/signup', {
      method: 'POST',
      body: { email: form.email, password: form.password },
    })
    await navigateTo('/staff/onboarding')
  } catch (error: unknown) {
    const msg =
      error && typeof error === 'object' && 'data' in error
        ? (error as { data?: { statusMessage?: string } }).data?.statusMessage
        : undefined
    errorMessage.value = msg ?? 'Sign up failed. Please try again.'
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <main class="app-surface">
    <div class="app-shell">
      <AppTopbar />

      <PageHeader
        eyebrow="Create account"
        title="Join Crown Valet"
        description="Create your staff account to get started."
      />

      <section class="app-card">
        <form class="check-in-form" @submit.prevent="signup">
          <div class="form-section">
            <label class="field">
              <span>Email</span>
              <input
                v-model="form.email"
                type="email"
                autocomplete="email"
                name="email"
                placeholder="you@example.com"
                required
              >
            </label>

            <label class="field">
              <span>Password</span>
              <input
                v-model="form.password"
                type="password"
                autocomplete="new-password"
                name="password"
                placeholder="••••••••"
                minlength="8"
                required
              >
            </label>

            <label class="field">
              <span>Confirm password</span>
              <input
                v-model="form.confirmPassword"
                type="password"
                autocomplete="new-password"
                name="confirm-password"
                placeholder="••••••••"
                required
              >
            </label>
          </div>

          <p v-if="errorMessage" class="form-error">{{ errorMessage }}</p>

          <div class="form-submit">
            <button class="button primary" type="submit" :disabled="isSubmitting">
              {{ isSubmitting ? 'Creating account…' : 'Create account' }}
            </button>
          </div>
        </form>

        <p class="signup-login-link">
          Already have an account?
          <NuxtLink to="/staff/login">Sign in</NuxtLink>
        </p>
      </section>
    </div>
  </main>
</template>

<style scoped>
.signup-login-link {
  margin-top: 1.25rem;
  text-align: center;
  font-size: 0.875rem;
  color: var(--color-ink);
  opacity: 0.7;
}

.signup-login-link a {
  color: var(--color-gold);
  text-decoration: none;
  font-weight: 600;
}

.signup-login-link a:hover {
  text-decoration: underline;
}
</style>
